### ISSUE TITLE
Página en blanco al cambiar contraseña de usuario

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#26]
En la edición de usuarios, si un usuario no tiene asignado un idioma por defecto y se activa la casilla para solicitar cambio de contraseña, la siguiente vez que el usuario intente iniciar sesión en un sitio, se le presentará una pantalla en blanco. Este issue es consecuencia de #15.

### Resultado esperado
Cuando un usuario inicia sesión en un sitio, si se ha solicitado cambio de contraseña, deberá presentarse el formulario correspondiente.

### Resultado obtenido
Pantalla en blanco en cambio de contraseña

### Pasos para reproducir el error

**Agregar un nuevo usuario**
1. Agregar un nuevo usuario a algún repositorio en el sitio de administración
2. No asignar idioma al usuario
3. Marcar la casilla _Solicitar cambio de contraseña_
4. Guardar los datos

**Iniciar sesión con el nuevo usuario**
1. Ingresar a alguna sección del sitio con restricción de acceso
2. Introducir el nombre de usuario y contraseña
3. Se muestra pantalla en blanco

### Log de la aplicación

```
ERROR - 
java.lang.NullPointerException
	at java.util.Locale.<init>(Locale.java:648)
	at java.util.Locale.<init>(Locale.java:701)
	at org.semanticwb.servlet.internal.Login.doProcess(Login.java:351)
	at org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SWBVirtualHostFilter.java:417)
	at org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFilter.java:332)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:105)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:361)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1080)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:75)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:757)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jordivs** [comment]
Este issue estaba asignado a @SergioMartinezP , @jajs1975  @softjei a quien le asignamos este issue?
