### ISSUE TITLE
Documentos del servidor no puede cargar clase del recurso

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#49]
Al abrir documentos del servidor, no se muestra el componente y en la consola se presenta lo siguiente:

```
2017-06-22 12:42:53,761 ERROR - Error Creating SWBResource: SWBAdmin-24
java.lang.ClassNotFoundException: org.semanticwb.portal.admin.resources.ServerDocumentsManager
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1139)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.semanticwb.portal.SWBResourceMgr.createSWBResourceClass(SWBResourceMgr.java:666)
	at org.semanticwb.portal.SWBResourceMgr.createSWBResourceClass(SWBResourceMgr.java:650)
	at org.semanticwb.portal.SWBResourceMgr.createSWBResource(SWBResourceMgr.java:707)
	at org.semanticwb.portal.SWBResourceMgr.getResource(SWBResourceMgr.java:253)
	at org.semanticwb.portal.SWBResourceMgr.getContents(SWBResourceMgr.java:311)
	at org.semanticwb.portal.util.SWBMethod.invoke(SWBMethod.java:215)
	at org.semanticwb.portal.TemplateImp.build(TemplateImp.java:1062)
	at org.semanticwb.portal.TemplateImp.build(TemplateImp.java:980)
	at org.semanticwb.servlet.internal.Distributor._doProcess(Distributor.java:453)
	at org.semanticwb.servlet.internal.Distributor.doProcess(Distributor.java:101)
	at org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SWBVirtualHostFilter.java:405)
	at org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFilter.java:332)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jordivs** [comment]
Ya se carga la clase
