### ISSUE TITLE
No se muestra la configuración de recursos administrables

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#70]
## Descripción
Al acceder a la pestaña de administración de los recursos que extienden de GenericAdmResource y usan un bundle xml para mostrar la configuración, no se muestra la interfaz.

<img width="745" alt="captura de pantalla 2017-08-28 a la s 11 53 02" src="https://user-images.githubusercontent.com/7064389/29784387-66f1b7d2-8be9-11e7-88d5-1666fd55557f.png">

En el log se presenta el siguiente error:

````
2017-08-28 11:51:00,940 ERROR - Error to process JSP.../swbadmin/jsp/editResource.jsp
org.apache.jasper.JasperException: Ha sucedido una excepción al procesar la página JSP /swbadmin/jsp/editResource.jsp en línea 30

27:             
28:             SWBHttpServletResponseWrapper resp=new SWBHttpServletResponseWrapper(response);
29:             
30:             sem.render(request, resp, req);
31:             
32:             out.print(resp.toString());
33:             


Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:578)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:719)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:583)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:522)
	at org.semanticwb.portal.resources.JSPResource.doView(JSPResource.java:91)
	at org.semanticwb.portal.api.GenericResource.processRequest(GenericResource.java:141)
	at org.semanticwb.portal.api.GenericResource.render(GenericResource.java:124)
	at org.semanticwb.portal.api.SWBResourceWindowRender.render(SWBResourceWindowRender.java:80)
	at org.semanticwb.portal.api.SWBResourceTraceMgr.renderTraced(SWBResourceTraceMgr.java:167)
	at org.semanticwb.portal.TemplateImp.build(TemplateImp.java:1098)
	at org.semanticwb.portal.TemplateImp.build(TemplateImp.java:934)
	at org.semanticwb.servlet.internal.Distributor._doProcess(Distributor.java:453)
	at org.semanticwb.servlet.internal.Distributor.doProcess(Distributor.java:101)
	at org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SWBVirtualHostFilter.java:392)
	at org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFilter.java:319)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:105)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:361)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1080)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:75)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:757)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.semanticwb.portal.SWBFormMgr.init(SWBFormMgr.java:179)
	at org.semanticwb.portal.SWBFormMgr.<init>(SWBFormMgr.java:143)
	at org.semanticwb.process.resources.taskinbox.UserTaskInboxResource.doAdmin(UserTaskInboxResource.java:550)
	at org.semanticwb.portal.api.GenericResource.processRequest(GenericResource.java:150)
	at org.semanticwb.process.resources.taskinbox.UserTaskInboxResource.processRequest(UserTaskInboxResource.java:254)
	at org.semanticwb.portal.api.GenericResource.render(GenericResource.java:124)
	at org.apache.jsp.swbadmin.jsp.editResource_jsp._jspService(editResource_jsp.java:152)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	... 37 more
````
JDK: Oracle JDK 1.8
Servidor de aplicaciones: Apache Tomcat 9.0.0
Sistema Operativo: Mac OSX 10.12.6
Navegador Web: Indistinto
Versión de SWBProcess: 5.0-beta.1

## Diagnóstico inicial
Al inicializar SWBPortal, se presenta el siguiente error en el log:

````
11:05:12.083 [localhost-startStop-1] WARN  u.l.g.dwr.impl.DefaultCreatorManager - Error setting class=org.chiba.web.flux.FluxFacade on uk.ltd.getahead.dwr.create.NewCreator
java.lang.IllegalArgumentException: Class not found: org.chiba.web.flux.FluxFacade
	at uk.ltd.getahead.dwr.create.NewCreator.setClass(NewCreator.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at uk.ltd.getahead.dwr.util.LocalUtil.setProperty(LocalUtil.java:281)
	at uk.ltd.getahead.dwr.impl.DefaultCreatorManager.addCreator(DefaultCreatorManager.java:105)
	at uk.ltd.getahead.dwr.impl.DefaultConfiguration.loadCreate(DefaultConfiguration.java:255)
	at uk.ltd.getahead.dwr.impl.DefaultConfiguration.loadAllows(DefaultConfiguration.java:196)
	at uk.ltd.getahead.dwr.impl.DefaultConfiguration.addConfig(DefaultConfiguration.java:90)
	at uk.ltd.getahead.dwr.impl.DefaultConfiguration.addConfig(DefaultConfiguration.java:66)
	at uk.ltd.getahead.dwr.AbstractDWRServlet.readFile(AbstractDWRServlet.java:188)
	at uk.ltd.getahead.dwr.DWRServlet.configure(DWRServlet.java:117)
	at uk.ltd.getahead.dwr.AbstractDWRServlet.init(AbstractDWRServlet.java:119)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4935)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5231)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:155)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:718)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1097)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1798)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
11:05:12.087 [localhost-startStop-1] ERROR u.l.g.dwr.impl.DefaultCreatorManager - Creator: 'NewCreator[Flux]' for Flux.js is returning null for type queries.
````

El proyecto chiba fue descontinuado desde 2009, ahora se llama [betterForm](https://github.com/betterFORM/betterFORM), por otro lado, el paquete de chiba-web en apache maven ya no existe, las referencias a su [espacio de nombres](http://chiba.sourceforge.net/xforms) no funcionan más.

## Issues relacionados
#30 
SemanticWebBuilder/SWBP#24

**Comment by haxdai** [comment]
Después de rastrear el issue, éste es ocasionado por #71.

**Comment by haxdai** [comment]
Caused by #71
