### ISSUE TITLE
Error al exportar en PDF los reportes

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#79]
Cuando se exporta en PDF los reportes de:

Reporte de accesos globales
Por dispositivo
Por idioma
Por sesiones
Usuarios firmados
Usuarios firmados unicos

se genera el siguiente error:
http://localhost:8080/es/SWBAdmin/WBAd_mnui_TopicReport/_rid/44/_mto/3/_mod/pdf?wb_site=basico&section=home&wb_rtype=0&wb_rep_type=1&wb_fecha1=2017-09-12&wb_fecha11=2017-09-01&wb_fecha12=2017-09-12

2017-09-12 11:32:26,393 ERROR - Attempt to process an HTTP-500: /es/SWBAdmin/WBAd_mnui_DeviceReportDaily/_rid/40/_mto/3/_mod/pdf - 500:Error to process request:/es/SWBAdmin/WBAd_mnui_DeviceReportDaily/_rid/40/_mto/3/_mod/pdf
2017-09-12 11:40:43,990 ERROR - Error on method doRepPdf() resource org.semanticwb.portal.admin.resources.reports.WBAGlobalReport with id 30
javax.servlet.ServletException: java.lang.NullPointerException
        at org.semanticwb.portal.admin.resources.reports.WBAGlobalReport.doRepPdf(WBAGlobalReport.java:802)
        at org.semanticwb.portal.admin.resources.reports.WBAGlobalReport.processRequest(WBAGlobalReport.java:131)
        at org.semanticwb.portal.admin.resources.reports.WBAGlobalReport.render(WBAGlobalReport.java:106)
        at org.semanticwb.portal.api.SWBResourceTraceMgr.renderTraced(SWBResourceTraceMgr.java:163)
        at org.semanticwb.servlet.internal.Distributor._doProcess(Distributor.java:304)
        at org.semanticwb.servlet.internal.Distributor.doProcess(Distributor.java:101)
        at org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SWBVirtualHostFilter.java:392)
        at org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFilter.java:319)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2620)
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2636)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3113)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:853)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
        at net.sf.jasperreports.engine.util.ContextClassLoaderObjectInputStream.<init>(ContextClassLoaderObjectInputStream.java:53)
        at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:193)
        at org.semanticwb.portal.admin.resources.reports.jrresources.JRResource.loadJasperResource(JRResource.java:151)
        at org.semanticwb.portal.admin.resources.reports.jrresources.JRResource.prepareReport(JRResource.java:121)
        at org.semanticwb.portal.admin.resources.reports.WBAGlobalReport.doRepPdf(WBAGlobalReport.java:799)
        ... 26 more

**Comment by haxdai** [comment]
@jordivs parece estar relacionado con #71

**Comment by jordivs** [comment]
Solucionado 53d5a5aa2e38ee9ce799b93730d707ef96ba13d8
