### ISSUE TITLE
En una instancia con contexto no se almacena archivos desde el HTMLContent porque no encuentra la ruta

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#84]
### Replicar incidencia
1.- Entrar al editor del componente HTMLContent 
2.- Subir un archivo con la opción de "Insertar/Editar vinculo"

### Resultado

Se muestra una ventana que indica "No se ha podido almacenar el archivo” ya que no encuentra la ruta 
![2017-09-13 at 17-55-48](https://user-images.githubusercontent.com/7914633/30404771-c905e404-98ad-11e7-80e4-f0d0fb2f0706.png)

### Excepción de Consola
2017-09-13 17:55:28,918 ERROR - No se ha podido almacenar el archivo
java.io.FileNotFoundException: /portal/home/centos/instanciasPruebas/no-applets/                             apache9.0.0.M17/webapps/portal/work/models/basico/Resource/60/1/images/Libro1.xl                             sx (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.apache.commons.fileupload.disk.DiskFileItem.write(DiskFileItem.ja                             va:394)
        at org.semanticwb.portal.resources.sem.HTMLContent.doUploadFiles(HTMLCon                             tent.java:168)
        at org.semanticwb.portal.resources.sem.HTMLContent.processRequest(HTMLCo                             ntent.java:591)
        at org.semanticwb.portal.api.GenericResource.render(GenericResource.java                             :124)
        at org.semanticwb.portal.api.SWBResourceTraceMgr.renderTraced(SWBResourc                             eTraceMgr.java:163)
        at org.semanticwb.servlet.internal.Distributor._doProcess(Distributor.ja                             va:304)
        at org.semanticwb.servlet.internal.Distributor.doProcess(Distributor.jav                             a:101)
        at org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SW                             BVirtualHostFilter.java:392)
        at org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFi                             lter.java:319)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                             icationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                             ilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV                             alve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV                             alve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica                             torBase.java:475)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j                             ava:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j                             ava:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAcce                             ssLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal                             ve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav                             a:341)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java                             :498)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig                             ht.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract                             Protocol.java:796)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo                             int.java:1368)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas                             e.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                             java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                             .java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh                             read.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by JRedentor** [comment]
Zafo!!!

**Comment by jordivs** [comment]
Listo!!
